name: Portl
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7295845826156437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1408'
    - '#eccdd1'
    - '#fffffe'
    - '#725a64'
    - '#176195'
  brandStrength: 1
  lightness: 0.40453011030331254
  saturation: 0.16163073433563113
  rhythmicContrast: 0.4150447922293097
purpose: []
